### ISSUE TITLE
求作者大大更新功能

### ISSUE THREAD

**Issue by Megatronworld** [Humorly/cloudcontpaste#3]
目前使用感觉良好挺好用的，很感谢作者。。。真是一个“极好的剪贴板”
反馈以下几点：1.窗口不可以随意拖拉大小。2.复制图片显示区域占用面积太大
最后提一个小小的建议，希望作者能加一个剪贴板收集开关。这样方便同时用两个同样的工具交互着使用，谢谢了

**Comment by Humorly** [comment]
> 目前使用感觉良好挺好用的，很感谢作者。。。真是一个“极好的剪贴板”
> 反馈以下几点：1.窗口不可以随意拖拉大小。2.复制图片显示区域占用面积太大
> 最后提一个小小的建议，希望作者能加一个剪贴板收集开关。这样方便同时用两个同样的工具交互着使用，谢谢了

感谢建议！已经收到，后续陆续添加哈！
