### ISSUE TITLE
Win7下连续按热键窗口抖动

### ISSUE THREAD

**Issue by tianxiayu007** [Humorly/cloudcontpaste#5]
按热键触发窗口，连续按的话，窗口会来回移动，随机的，不知道啥情况

**Comment by tianxiayu007** [comment]
按热键窗口跟着鼠标走，这是软件的特性吗 能否改成可配置  窗口抖动经常要重新定位到底要选择哪一项
![GIF 2022-05-13 17-00-32](https://user-images.githubusercontent.com/3746672/168249632-0ba599cf-786c-4ff0-a4ff-24c5aac558f5.gif)

**Comment by Humorly** [comment]
列表中有多条数据之后，按下热键不松开会在多条数据之间循环切换。按热键窗口跟着鼠标走，这是软件的特性，不跟着鼠标移动而设定在固定的位置窗口可能会盖住鼠标。

**Comment by tianxiayu007** [comment]
> 列表中有多条数据之后，按下热键不松开会在多条数据之间循环切换。按热键窗口跟着鼠标走，这是软件的特性，不跟着鼠标移动而设定在固定的位置窗口可能会盖住鼠标。

还有1个问题，我只是想呼出窗口查看内容，不想按完热键窗口就消失了怎么办呢？虽然可以手动点击激活窗口，但最好还是新增1个热键激活窗口比较妥帖吧。。。

**Comment by Humorly** [comment]
> > 列表中有多条数据之后，按下热键不松开会在多条数据之间循环切换。按热键窗口跟着鼠标走，这是软件的特性，不跟着鼠标移动而设定在固定的位置窗口可能会盖住鼠标。
> 
> 
> 
> 还有1个问题，我只是想呼出窗口查看内容，不想按完热键窗口就消失了怎么办呢？虽然可以手动点击激活窗口，但最好还是新增1个热键激活窗口比较妥帖吧。。。

这个可以考虑哈

**Comment by tianxiayu007** [comment]
另外，连续按热键会依次向下滚动选择条目，有没有反向滚动选择条目的快捷键呢？

**Comment by Humorly** [comment]
> 另外，连续按热键会依次向下滚动选择条目，有没有反向滚动选择条目的快捷键呢？

目前没有此快捷键

**Comment by Humorly** [comment]
> > > 列表中有多条数据之后，按下热键不松开会在多条数据之间循环切换。按热键窗口跟着鼠标走，这是软件的特性，不跟着鼠标移动而设定在固定的位置窗口可能会盖住鼠标。
> > 
> > 
> > 还有1个问题，我只是想呼出窗口查看内容，不想按完热键窗口就消失了怎么办呢？虽然可以手动点击激活窗口，但最好还是新增1个热键激活窗口比较妥帖吧。。。
> 
> 这个可以考虑哈

现在窗口可以选择不自动隐藏了哈

**Comment by Humorly** [comment]
> Author

反向快捷键目前没有想到好的解决方案，如果再做一套所有快捷键的反向按键，感觉键位有点多，感觉有点整复杂了

**Comment by deyuren** [comment]
ctrl +q 会闪退 是正常的吗 第一次使用时没有闪退 现在过了3小时 ctrl+q 闪退
