### ISSUE TITLE
没有一键清空列表数据的功能

### ISSUE THREAD

**Issue by tianxiayu007** [Humorly/cloudcontpaste#6]
加上不是更方便吗 有些文档比较类似，清空重新复制不易出错

**Comment by Humorly** [comment]
在列表处 CTRL + A全选，然后用右键菜单删除或者按下delete键 删除

**Comment by tianxiayu007** [comment]
> 在列表处 CTRL + A全选，然后用右键菜单删除或者按下delete键 删除

啊这 也可以
