### ISSUE TITLE
可不可以修改软件的字体

### ISSUE THREAD

**Issue by ZDY321** [Humorly/cloudcontpaste#7]
可不可以修改软件的字体。win免费版的安装完之后，剪贴板历史内容的字体很丑
![image](https://user-images.githubusercontent.com/81518210/184615924-1136be6b-01cb-44eb-aab7-b220f67663bb.png)

**Comment by Humorly** [comment]
有空会加上哈

**Comment by Humorly** [comment]
windows上已经全部切换成微软雅黑了哈
