### ISSUE TITLE
怎么去掉快捷键？

### ISSUE THREAD

**Issue by Top-Chen0** [Humorly/cloudcontpaste#8]
直接占用 ctrl T、R、E、W这就很不人性化很劝退，如果这个功能不改真的没法用这个软件

**Comment by Humorly** [comment]
先改个无效的快捷键占用一下，后面修复这个问题

**Comment by Humorly** [comment]
> 直接占用 ctrl T、R、E、W这就很不人性化很劝退，如果这个功能不改真的没法用这个软件

你好，steam已更新，可以关闭快捷键
